# Generated by Django 2.2.5 on 2019-09-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
