# Generated by Django 2.2.5 on 2019-09-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0003_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='quoteApp.User'),
        ),
    ]
