# Generated by Django 2.2.5 on 2019-09-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0004_auto_20190925_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='quoteApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.CharField(max_length=255),
        ),
    ]
