# Generated by Django 2.2.5 on 2019-09-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0005_auto_20190926_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='poster',
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='quoteApp.User'),
        ),
    ]
