# Generated by Django 2.2.5 on 2019-09-26 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp', '0006_auto_20190926_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='quoteApp.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoter',
            field=models.CharField(max_length=255),
        ),
    ]
