# Generated by Django 2.2.5 on 2019-09-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='poster',
            field=models.ForeignKey(null='None', on_delete=django.db.models.deletion.CASCADE, related_name='quotes_created', to='quoteApp2.User'),
        ),
    ]
