# Generated by Django 2.2.5 on 2019-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteApp2', '0002_auto_20190926_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_quote', to='quoteApp2.User'),
        ),
    ]
